"""add travel package schema

Revision ID: 8a9218b80be6
Revises: 51f5cbd72d2b
Create Date: 2026-10-04 12:32:42.943003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9218b80be6'
down_revision: Union[str, Sequence[str], None] = '51f5cbd72d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), server_default='India', nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=True)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_name'), 'hotels', ['name'], unique=False)
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('duration_nights', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='INR', nullable=False),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_destination_id'), 'packages', ['destination_id'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_package_id'), 'bookings', ['package_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('package_days',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'day_number', name='uq_package_day_number')
    )
    op.create_index(op.f('ix_package_days_package_id'), 'package_days', ['package_id'], unique=False)
    op.create_table('package_hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('nights', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'hotel_id', name='uq_package_hotel')
    )
    op.create_index(op.f('ix_package_hotels_hotel_id'), 'package_hotels', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_package_hotels_package_id'), 'package_hotels', ['package_id'], unique=False)
    op.create_table('package_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=32), server_default='image', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_media_destination_id'), 'package_media', ['destination_id'], unique=False)
    op.create_index(op.f('ix_package_media_package_id'), 'package_media', ['package_id'], unique=False)
    op.create_table('package_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_day_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_note', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['package_day_id'], ['package_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_stops_package_day_id'), 'package_stops', ['package_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_stops_package_day_id'), table_name='package_stops')
    op.drop_table('package_stops')
    op.drop_index(op.f('ix_package_media_package_id'), table_name='package_media')
    op.drop_index(op.f('ix_package_media_destination_id'), table_name='package_media')
    op.drop_table('package_media')
    op.drop_index(op.f('ix_package_hotels_package_id'), table_name='package_hotels')
    op.drop_index(op.f('ix_package_hotels_hotel_id'), table_name='package_hotels')
    op.drop_table('package_hotels')
    op.drop_index(op.f('ix_package_days_package_id'), table_name='package_days')
    op.drop_table('package_days')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_package_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_destination_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_name'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
